---
## Sets up public key authentication on hosts with newly installed Raspbian.
- name: Authentication setup

  hosts: all
  gather_facts: no

  vars_prompt:
    - name: 'ssh_public_key_path'
      prompt: 'Where is your SSH public key?'
      default: '~/.ssh/id_rsa.pub'
      private: no
    - name: 'pi_user_password'
      prompt: "What should the new password for the user 'pi' be?"
      private: yes
      encrypt: 'sha512_crypt'
      confirm: yes
      salt_size: 12

  tasks:
    - name: Add SSH key for passwordless login (pi).
      authorized_key:
        user: pi
        key: '{{ item }}'
      with_file:
        - '{{ ssh_public_key_path }}'

    - name: Change default password (pi).
      become: yes
      user:
        name: pi
        password: '{{ pi_user_password }}'
