---
## Configures and deploys Homebase and dependencies on Pis.

- name: Configures and deploys Homebase and dependencies on Pi(s).
  hosts: all
  remote_user: pi
  become: yes
  vars_files:
    - vars/main.yaml
  vars_prompt:
    - name: 'letsencrypt_email'
      prompt: 'What email would you like to use for letsencrypt?'
      private: no
  roles:
    - basic_config
    - basic_packages
    - geerlingguy.security
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.nodejs
    - homebase_config
