---
## Configures and deploys Homebase and dependencies on Pis.

- name: Configures and deploys Homebase and dependencies on Pi(s).
  hosts: all
  remote_user: pi
  become: yes

  vars_files:
    - vars/main.yaml

  vars_prompt:
    - name: 'dat_url'
      prompt: 'Enter the url of a DAT you wish to pin.'
      private: no
    - name: 'https_mirror_domain'
      prompt: 'Enter the domain name you wish to mirror your DAT to.'
      private: no
    - name: 'letsencrypt_email'
      prompt: 'What email would you like to use for letsencrypt?'
      private: no

  roles:
    - basic_config
    - basic_packages
    - geerlingguy.security
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.nodejs
    - nginx_config
    - certbot
    - homebase
