- name: Add apt repository for certbot
  apt_repository:
    repo: 'ppa:certbot/certbot'
    codename: trusty

- name: Update apt package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install nginx
  package:
    name: nginx
    state: present

- name: Install python-certbot-nginx
  package:
    name: python-certbot-nginx
    state: present

- name: Install git
  package:
    name: git
    state: present

- name: Install vim
  package:
    name: vim
    state: present

- name: Upgrade apt packages
  apt:
    upgrade: safe

#- name: Reboot the server to avoid issues with iptables setup.
#  reboot:
